// Skydancer adapter. Geometry and rules remain reusable without game globals.
const autumnWorld=(()=>{
 let ready=false,kit,regions=[],beds=[],timer=0,carry,crate,roads=[],obstacles=[],fieldFruit=new Map();
 const R=window.AutumnRules,A=window.AutumnAssets,get=()=>R.ensure(homestead.state),tier=()=>settings.quality==='high'?'high':settings.quality==='balanced'?'medium':'mobile';
 function distanceSegment(x,z,a,b){const dx=b.x-a.x,dz=b.z-a.z,t=Math.max(0,Math.min(1,((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz||1)));return Math.hypot(x-a.x-t*dx,z-a.z-t*dz);}
 function suitable(x,z){const o=homestead.origin;if(Math.abs(x-o.x)<5.6&&z-o.z>-5&&z-o.z<11)return false;const lc=pagosaWorld.landClass(x,z);if([11,12,21,22,23,24,31].includes(lc))return false;const water=pagosaWorld.ecology.riverAt(x,z);if(water&&water.distance<water.halfWidth+1.5)return false;for(const r of roads)for(let i=1;i<r.points.length;i++)if(distanceSegment(x,z,r.points[i-1],r.points[i])<5)return false;
 const p=new THREE.Vector3(x,heightAt(x,z)+.2,z),old=p.clone().add(new THREE.Vector3(.25,0,.25)),probe=p.clone();pagosaWorld.ecology.collide(probe,old,.4);homestead.collide(probe,old);frontier.collide(probe,old,.4);if(Math.hypot(probe.x-p.x,probe.z-p.z)>.01)return false;return true;}
 function terrainAt(x,z){return {heightAt:(a,b)=>heightAt(x+a,z+b),suitable:(a,b)=>suitable(x+a,z+b)};}
 function makeRegion(spec){const x=homestead.origin.x+spec.x,z=homestead.origin.z+spec.z;const r=A.build(THREE,{tier:kit.tier,season:'early-fall',...spec},terrainAt(x,z),kit);r.root.position.set(x,0,z);scene.add(r.root);return r;}
 function bedActions(i){const s=get(),p=s?.plots[i];if(!p)return [];const prefix='autumn:'+i+':';beds[i].target.label='Pumpkin bed '+(i+1)+' · '+(p.planted?Math.floor(p.growth/2.4)+'% · '+(p.water?'damp':'dry'):'empty');return p.planted?(p.growth>=240?[['Harvest pumpkin',prefix+'harvest']]:[['Water pumpkin',prefix+'water']]):[['Plant pumpkin ('+s.seeds+' seeds)',prefix+'plant']];}
 function rebuildBed(i){const p=get()?.plots[i],b=beds[i];b.patch?.dispose();b.patch=null;if(!p?.planted)return;const stage=Math.max(.12,p.growth/240);b.patch=makeRegion({x:b.x,z:b.z,seed:p.seed,width:1,length:1,density:1,scale:.9,growth:stage,vineLength:1.2,branching:1,trellis:'off'});b.bucket=Math.floor(stage*6);}
 function register(id,x,z,label,actions){homestead.register(id,x,heightAt(homestead.origin.x+x,homestead.origin.z+z)-homestead.origin.y+.45,z,label,actions);return homestead.targets.at(-1);}
 function build(){if(ready||!homestead.ready)return;const s=get();if(!s){console.warn('Autumn save retained without modification');return;}kit=A.createKit(THREE,tier());const fd=pagosaWorld.fieldData();roads=fd.roads.filter(r=>r.points.some(p=>Math.hypot(p.x-homestead.origin.x,p.z-homestead.origin.z)<350));
 const specs=[{name:'Homestead pumpkin patch',x:-20,z:14,width:11,length:9,density:.24,seed:19351},{name:'Cabin climbing arch',x:9,z:-3,width:4,length:4,density:.13,trellis:'arch',seed:19352},{name:'Harvest field',x:36,z:27,width:32,length:24,density:.38,seed:19353},{name:'Barn doorstep pumpkins',x:pagosaWorld.site.shed.x-homestead.origin.x+5,z:pagosaWorld.site.shed.z-homestead.origin.z+6,width:3,length:3,density:.5,leafDensity:.2,vineLength:.4,seed:19354},{name:'Old fence runners',x:13,z:17,width:6,length:3,density:.22,trellis:'fence',trellisWidth:4,seed:19355}];
 regions=specs.map(spec=>({spec,patch:null}));for(let i=0;i<4;i++){const b={x:-12-(i%2)*2.4,z:-2+Math.floor(i/2)*2.8};beds.push(b);b.target=register('autumn-bed-'+i,b.x,b.z,'Pumpkin bed '+(i+1),()=>bedActions(i));rebuildBed(i);}
 crate=new THREE.Group();crate.name='Pumpkin storage crate';crate.position.set(homestead.origin.x+2.6,heightAt(homestead.origin.x+2.6,homestead.origin.z+7),homestead.origin.z+7);const gm=new THREE.BoxGeometry(1,.09,.075);for(let y=0;y<3;y++)for(const z of [-.4,.4]){const m=new THREE.Mesh(gm,kit.materials.timber);m.position.set(0,.12+y*.14,z);m.castShadow=true;crate.add(m);}for(const x of [-.5,.5]){const m=new THREE.Mesh(new THREE.BoxGeometry(.07,.5,.9),kit.materials.timber);m.position.set(x,.25,0);crate.add(m);}scene.add(crate);register('autumn-store',2.6,7,'Pumpkin crate',()=>[['Store carried pumpkin · '+get().stored+' stored','autumn:store']]);
 carry=new THREE.Group();carry.name='Carried pumpkin';const mat=kit.materials.fruit.clone();mat.color.setHex(0xe07918).convertSRGBToLinear();carry.add(new THREE.Mesh(kit.fruit(0),mat),new THREE.Mesh(kit.stem(0),kit.materials.stem));carry.scale.setScalar(.8);carry.visible=false;scene.add(carry);ready=true;
 const b=document.createElement('button');b.className='btn';b.textContent='Autumn garden';ui.go.parentNode.insertBefore(b,ui.go.nextSibling);bindTap(b,()=>{endIntro();homestead.enter();const p=currentActor().root.position;p.set(homestead.origin.x-12,heightAt(homestead.origin.x-12,homestead.origin.z+4),homestead.origin.z+4);crewLook.yaw=0;crewCamera(1);toast('Pumpkin beds beside the cabin. Harvest with empty hands; store at the porch crate.');});
 }
 function registerRegionFruit(region){const patch=region.patch,items=new Map(),m=new THREE.Matrix4(),p=new THREE.Vector3();patch.root.traverse(mesh=>{if(!mesh.isInstancedMesh||!['fruit','stem'].includes(mesh.material.name))return;for(let i=0;i<mesh.count;i++){mesh.getMatrixAt(i,m);p.setFromMatrixPosition(m).add(patch.root.position);const key=region.spec.seed+':'+p.x.toFixed(3)+':'+p.z.toFixed(3);let item=items.get(key);if(!item){item={key,point:p.clone(),refs:[]};items.set(key,item);}item.refs.push({mesh,index:i});}});for(const item of items.values()){fieldFruit.set(item.key,item);const point=item.point.clone().sub(homestead.origin);homestead.register('autumn-field-'+item.key,point.x,point.y+.3,point.z,'Ripe field pumpkin',()=>get().picked.includes(item.key)?[]:[['Harvest pumpkin','autumn:field:'+item.key]]);item.target=homestead.targets.at(-1);if(get().picked.includes(item.key))hideFruit(item);}}
 function hideFruit(item){const m=new THREE.Matrix4();for(const r of item.refs){r.mesh.getMatrixAt(r.index,m);m.scale(new THREE.Vector3(0,0,0));r.mesh.setMatrixAt(r.index,m);r.mesh.instanceMatrix.needsUpdate=true;}item.target.range=0;}
 function handle(id){if(!id.startsWith('autumn:'))return false;const s=get();if(!s)return true;if(id.startsWith('autumn:field:')){const key=id.slice(13),item=fieldFruit.get(key);if(!item||s.picked.includes(key))return true;if(s.picked.length>=2000){toast('Field harvest save limit reached');return true;}const before=s.carried;toast(R.act(homestead.state,'gather'));if(!before&&s.carried){s.picked.push(key);hideFruit(item);homestead.save();}return true;}const fields=id.split(':'),action=fields[1]==='store'?'store':fields[2],i=Number(fields[1]),before=JSON.stringify(s);toast(R.act(homestead.state,action,i));if(JSON.stringify(s)!==before){if(Number.isInteger(i)&&beds[i])rebuildBed(i);homestead.save();}return true;}
 function update(dt){if(!ready)return;const s=get();if(!s)return;R.tick(homestead.state,dt);timer+=dt;kit.clock.value=elapsed;
 for(const r of regions){const p=new THREE.Vector3(homestead.origin.x+r.spec.x,0,homestead.origin.z+r.spec.z),distance=Math.hypot(camera.position.x-p.x,camera.position.z-p.z);if(!r.patch&&distance<kit.q.cull){r.patch=makeRegion(r.spec);r.patch.root.name=r.spec.name;registerRegionFruit(r);}if(r.patch)r.patch.update(camera,elapsed);}
 for(const b of beds)b.patch?.update(camera,elapsed);if(timer>4){timer=0;beds.forEach((b,i)=>{const p=s.plots[i],bucket=Math.floor(Math.max(.12,p.growth/240)*6);if(p.planted&&bucket!==b.bucket)rebuildBed(i);});}
 const h=homestead.state,a=currentActor(),hands=h.activities.tool==='hands'&&h.rod!=='equipped'&&h.wilds.hunt.gun!=='carried'&&!h.pack.wood;carry.visible=!!s.carried&&hands&&state==='flying'&&!crew.aboard;if(carry.visible){carry.position.copy(a.root.position).add(new THREE.Vector3(0,.9,-.36).applyAxisAngle(V_UP,a.root.rotation.y));carry.rotation.y=a.root.rotation.y;}
 }
 function present(){if(!carry?.visible||activities.busy||fishing.busy)return;const g=currentActor().gameplay;if(!g?.gripFrame)return;const center=carry.position.clone().add(new THREE.Vector3(0,.16,0));for(const side of ['l','r']){const t=center.clone().add(new THREE.Vector3(side==='l'?.23:-.23,-.02,0).applyAxisAngle(V_UP,currentActor().root.rotation.y));const f=g.gripFrame(side),w=g.bones['hand_'+side].getWorldPosition(new THREE.Vector3());g.reach(side,t.sub(f.position.sub(w)),g.modelPoint(side==='l'?.55:-.55,.85,0,new THREE.Vector3()));g.grip(side,.45);}}
 return {build,handle,update,present,suitable,get ready(){return ready;},get state(){return get();},get regions(){return regions;},get beds(){return beds;},get carry(){return carry;},get stats(){return regions.map(r=>({name:r.spec.name,...r.patch?.stats()}));}};
})();
