const fs=require('node:fs'),path=require('node:path');const root=path.resolve(__dirname,'..'),dest=path.join(root,'assets/autumn/v0.3.0');fs.mkdirSync(dest,{recursive:true});
(async()=>{const tabs=await(await fetch('http://127.0.0.1:9275/json')).json(),ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0,pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);}};const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id,t=setTimeout(()=>reject(Error('timeout '+method)),90000);pending.set(n,m=>{clearTimeout(t);m.error?reject(Error(JSON.stringify(m.error))):resolve(m.result)});ws.send(JSON.stringify({id:n,method,params}));});const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
await send('Page.navigate',{url:(process.env.AUTUMN_PREVIEW_URL||'http://127.0.0.1:8136/autumn.html')});for(let i=0;i<60;i++){if(await ev('!!window.autumnPreview'))break;await new Promise(r=>setTimeout(r,250));}
const assets=[];for(const tier of ['mobile','medium','high']){
await ev('document.getElementById("tier").value='+JSON.stringify(tier)+';autumnPreview.setView("pumpkin")');
const names=['pumpkin-round','pumpkin-tall','pumpkin-squat','pumpkin-flat','pumpkin-white','pumpkin-green','pumpkin-warty','woody-stem','leaf-green','leaf-yellow','leaf-damaged','leaf-veins','male-blossom','female-blossom','vine-tendril','metal-arch','wooden-trellis','fence','trellis-modules'];
for(let index=0;index<names.length;index++){const name=names[index],result=await ev(`(async()=>{const T=THREE,k=autumnPreview.kit,g=new T.Group(),i=${index},name=${JSON.stringify(name)};const add=(geo,mat)=>{const m=new T.Mesh(geo,mat);g.add(m);return m;};if(i<7){const mat=k.materials.fruit.clone();mat.color.setHex([0xe07918,0xd86414,0xe49730,0xb96826,0xe9dfb3,0x647950,0xb37e36][i]).convertSRGBToLinear();add(k.fruit(i),mat);add(k.stem(i),k.materials.stem);}else if(i===7){const geo=k.stem(0).clone();geo.translate(0,-k.fruit(0).userData.socket[1],0);add(geo,k.materials.stem);}else if(i>=8&&i<=10){const mat=k.materials.leaf.clone();mat.color.setHex([0x467830,0xaaa343,0x817140][i-8]).convertSRGBToLinear();add(k.leaf(0,i-8),mat);if(i===8)add(k.veins(),k.materials.vein);}else if(i===11)add(k.veins(),k.materials.vein);else if(i===12||i===13){add(k.flower(),k.materials.flower);add(k.tube([[0,0,0],[0,-.1,0],[.03,-.18,0]],.009,5),k.materials.vine);if(i===13){const m=add(k.fruit(0),k.materials.fruit);m.scale.setScalar(.12);m.position.y=-.1;}}else if(i===14){const p=AutumnAssets.build(T,{width:1,length:1,density:1,tier:${JSON.stringify(tier)},growth:.2,seed:1935,branching:2,vineLength:1.7},{},k);g.add(p.root);}else if(i<18){add(k.trellis(AutumnAssets.options({trellis:['arch','wooden','fence'][i-15]})),i===15?k.materials.metal:k.materials.timber);}else{const pieces=[k.tube([[0,0,0],[0,1,0]],.025,8),k.tube([[.25,0,0],[.25,.3,0],[.4,.45,0]],.025,8),k.tube([[.6,0,0],[.6,.3,0]],.032,8),k.tube([[.5,.15,0],[.7,.15,0]],.032,8),k.tube([[.9,0,0],[.9,.4,0]],.02,8),k.tube([[1.1,0,0],[1.45,.45,0]],.018,8)];pieces.forEach((geo,j)=>{const m=add(geo,k.materials.metal);m.name=['straight-pipe','curved-elbow','sleeve-connector','cross-joint','ground-stake','diagonal-brace'][j];});}
g.name=name;g.updateMatrixWorld(true);let triangles=0;g.traverse(m=>{if(m.isMesh)triangles+=(m.geometry.index?.count||m.geometry.attributes.position.count)/3*(m.isInstancedMesh?m.count:1);});const box=new T.Box3().setFromObject(g),bytes=await autumnPreview.glb(g),arr=new Uint8Array(bytes);let b='';for(let j=0;j<arr.length;j+=8192)b+=String.fromCharCode(...arr.subarray(j,j+8192));if(!window._autumnThumb){const rr=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});rr.setSize(320,320);rr.outputEncoding=T.sRGBEncoding;rr.toneMapping=T.ACESFilmicToneMapping;window._autumnThumb=rr;}const ts=new T.Scene();ts.background=new T.Color(0x29332b);ts.add(new T.HemisphereLight(0xe4edff,0x6b5033,1.2));const light=new T.DirectionalLight(0xffeac4,1.7);light.position.set(-3,5,4);ts.add(light);ts.add(g);const size=box.getSize(new T.Vector3()).length(),center=box.getCenter(new T.Vector3()),tc=new T.PerspectiveCamera(40,1,.005,100);tc.position.copy(center).add(new T.Vector3(size*.7,size*.55,size*1.1));tc.lookAt(center);window._autumnThumb.render(ts,tc);const thumb=window._autumnThumb.domElement.toDataURL('image/png').split(',')[1];ts.remove(g);return {data:btoa(b),thumbnail:thumb,triangles,bounds:{min:box.min.toArray(),max:box.max.toArray()}};})()`);
const file=tier+'/'+name+'.glb';fs.mkdirSync(path.dirname(path.join(dest,file)),{recursive:true});fs.writeFileSync(path.join(dest,file),Buffer.from(result.data,'base64'));fs.writeFileSync(path.join(dest,tier,name+'.png'),Buffer.from(result.thumbnail,'base64'));assets.push({thumbnail:tier+'/'+name+'.png',id:name+'-'+tier,name,tier,file,triangles:result.triangles,bounds:result.bounds});console.log('EXPORTED',file,result.triangles);
}
}
const textures=await ev('Object.fromEntries(Object.entries(autumnPreview.kit.materialMaps).map(([name,ts])=>[name,ts.map(t=>t.image.toDataURL("image/png").split(",")[1])]))');fs.mkdirSync(path.join(dest,'materials'),{recursive:true});for(const [name,maps] of Object.entries(textures))maps.forEach((b,i)=>fs.writeFileSync(path.join(dest,'materials',name+'-'+['baseColor','normal','roughness','height'][i]+'.png'),Buffer.from(b,'base64')));
const manifest={schema:'autumn-procedural-pack-v1',version:'0.3.0',units:'metres',up:'Y',license:'MIT',provenance:{original:true,method:'Original analytic meshes and procedural PBR maps authored for the user. Three photo references and generated orthographic reference were visually consulted; no reference image pixels used in textures.',source:'web/src/autumn-core.js',referenceRights:'Reference photos are not redistributed; source ownership unverified.',humanVisualApproval:false},assets,qualityNotes:['Runtime wind is a Three.js shader; exported GLB is static.','Height maps are supplied separately; glTF does not encode displacement.','Normal and roughness maps are procedural, not scanned.'],review:'Technical candidate; awaiting user visual review'};fs.writeFileSync(path.join(dest,'manifest.json'),JSON.stringify(manifest,null,2));fs.copyFileSync(root+'/src/autumn-core.js',dest+'/autumn-core.js');fs.writeFileSync(dest+'/presets.json',JSON.stringify({homestead:{seed:19351,width:11,length:9,density:.24},field:{seed:19353,width:32,length:24,density:.38},arch:{seed:19352,width:4,length:4,density:.13,trellis:'arch'},fence:{seed:19355,width:6,length:3,density:.22,trellis:'fence'}},null,2));console.log('PACK_EXPORTED',assets.length);ws.close();})().catch(e=>{console.error(e);process.exit(1)});
