const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const base=path.resolve(__dirname,'..'),out=path.join(base,'.qa/autumn');fs.mkdirSync(out,{recursive:true});
(async()=>{const tabs=await(await fetch('http://127.0.0.1:'+(process.env.AUTUMN_QA_PORT||9275)+'/json')).json(),ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let n=0,pending=new Map(),errors=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++n,timer=setTimeout(()=>reject(Error(method+' timeout')),120000);pending.set(id,m=>{clearTimeout(timer);m.error?reject(Error(JSON.stringify(m.error))):resolve(m.result)});ws.send(JSON.stringify({id,method,params}));});
const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result?.value;};
const wait=ms=>new Promise(r=>setTimeout(r,ms));await send('Runtime.enable');await send('Page.enable');errors=[];
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await send('Page.navigate',{url:(process.env.AUTUMN_PREVIEW_URL||'http://127.0.0.1:8136/autumn.html')});
for(let i=0;i<80;i++){if(await ev('!!window.autumnPreview'))break;await wait(250);}assert(await ev('!!window.autumnPreview'),'Preview boot');assert.equal(await ev('document.getElementById("error").textContent'),'');errors=[];
const shot=async name=>{await wait(500);const s=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(out+'/'+name+'.png',Buffer.from(s.data,'base64'));};
await send('Page.bringToFront');await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await wait(1000);console.log('HIT',await ev('({w:innerWidth,h:innerHeight,target:document.elementFromPoint(180,370)?.id,enabled:autumnPreview.controls.enabled})'));await ev('window.__inputLog=[];["pointerdown","pointermove","pointerup"].forEach(k=>document.addEventListener(k,e=>__inputLog.push([k,e.target.id,e.pointerType])))');const before=await ev('autumnPreview.camera.position.toArray()');await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:370}]});await wait(70);for(let i=0;i<6;i++){await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:180+i*12,y:370+i*3}]});await wait(35);}await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(400);console.log('INPUT',await ev('__inputLog'));assert.notDeepEqual(await ev('autumnPreview.camera.position.toArray()'),before);
const dist=await ev('autumnPreview.camera.position.distanceTo(autumnPreview.controls.target)');await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:0,x:140,y:350},{id:1,x:240,y:350}]});await wait(70);await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:0,x:100,y:360},{id:1,x:280,y:360}]});await wait(70);await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(400);assert.notEqual(await ev('autumnPreview.camera.position.distanceTo(autumnPreview.controls.target)'),dist);
await ev('document.getElementById("controlsToggle").click()');assert(await ev('document.getElementById("panel").classList.contains("open")'));const seed=await ev('JSON.stringify(autumnPreview.patch.data.plants)');await ev('document.getElementById("shuffle").click()');assert.notEqual(await ev('JSON.stringify(autumnPreview.patch.data.plants)'),seed);await ev('document.getElementById("density").value=".6";document.getElementById("scale").value="1.2";autumnPreview.generate();document.getElementById("controlsToggle").click();document.getElementById("reset").click()');assert.equal(await ev('autumnPreview.patch.data.options.scale'),1.2);assert.equal(await ev('autumnPreview.patch.data.options.density'),.6);
const results={touchOrbit:true,touchPinch:true,controls:true,seed:true,scale:true,density:true,views:{},tiers:{},errors:[]};for(const v of ['field','pumpkin','leaf','vine','trellis']){await ev('autumnPreview.setView('+JSON.stringify(v)+')');await wait(900);assert.equal(await ev('document.getElementById("error").textContent'),'');assert((await ev('autumnPreview.renderer.info.render.triangles'))>0);results.views[v]=await ev('autumnPreview.stats');await shot('mobile-'+v);}
await ev('document.getElementById("width").value=26;document.getElementById("length").value=20;document.getElementById("density").value=.6;document.getElementById("scale").value=1;autumnPreview.setView("field")');
for(const tier of ['mobile','medium','high']){await ev('document.getElementById("tier").value='+JSON.stringify(tier)+';autumnPreview.generate(true)');await wait(1600);results.tiers[tier]=await ev('autumnPreview.stats');assert(results.tiers[tier].patch.plants>=200);assert(results.tiers[tier].render.calls<500);}
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await ev('document.getElementById("width").value=12;document.getElementById("length").value=10;document.getElementById("density").value=.4;autumnPreview.setView("field")');await shot('desktop-field');await ev('autumnPreview.setView("pumpkin")');await shot('desktop-pumpkins');await ev('autumnPreview.setView("trellis")');await shot('desktop-trellis');
assert.equal(errors.length,0,JSON.stringify(errors));results.errors=errors;results.device='Windows Chrome headless; mobile viewport + synthetic touch; not iPhone Safari';fs.writeFileSync(out+'/preview-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));ws.close();})().catch(e=>{console.error(e);process.exit(1)});
