(function(){'use strict';
const $=id=>document.getElementById(id),T=THREE,A=AutumnAssets,canvas=$('view');let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('error').textContent='3D could not start. Close other browser tabs and reload. '+e.message;return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color(0x8fa2a1);scene.fog=new T.Fog(0x8fa2a1,65,150);const camera=new T.PerspectiveCamera(43,1,.015,180),controls=new T.OrbitControls(camera,canvas);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=.35;controls.maxDistance=85;controls.target.set(0,.25,0);camera.position.set(8,7,11);
scene.add(new T.HemisphereLight(0xd6e9f2,0x62502b,.65));const sun=new T.DirectionalLight(0xffecc9,2.6);sun.position.set(-8,13,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-18,right:18,top:18,bottom:-18,near:1,far:60});sun.shadow.bias=-.0002;sun.shadow.normalBias=.018;scene.add(sun);scene.add(new T.AmbientLight(0xffffff,.04));
const soilCanvas=document.createElement('canvas');soilCanvas.width=soilCanvas.height=256;const ctx=soilCanvas.getContext('2d'),im=ctx.createImageData(256,256),rand=A.rng(77);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const v=rand()*22+Math.sin(x*.079+Math.sin(y*.053)*2)*3+Math.sin(y*.12+x*.031)*3,i=(y*256+x)*4;im.data.set([55+v,42+v,26+v,255],i);}ctx.putImageData(im,0,0);const soilMap=new T.CanvasTexture(soilCanvas);soilMap.wrapS=soilMap.wrapT=T.RepeatWrapping;soilMap.repeat.set(45,45);soilMap.encoding=T.sRGBEncoding;const soilMat=new T.MeshStandardMaterial({map:soilMap,bumpMap:soilMap,bumpScale:.009,envMapIntensity:.12,roughness:1});const ground=new T.Mesh(new T.PlaneGeometry(150,150,70,70),soilMat);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const skyCanvas=document.createElement('canvas');skyCanvas.width=512;skyCanvas.height=256;const skyCtx=skyCanvas.getContext('2d'),gradient=skyCtx.createLinearGradient(0,0,0,256);gradient.addColorStop(0,'#668ba9');gradient.addColorStop(.48,'#d6e1dd');gradient.addColorStop(.52,'#a6a58c');gradient.addColorStop(1,'#423828');skyCtx.fillStyle=gradient;skyCtx.fillRect(0,0,512,256);const skyTexture=new T.CanvasTexture(skyCanvas);skyTexture.mapping=T.EquirectangularReflectionMapping;skyTexture.encoding=T.sRGBEncoding;const pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromEquirectangular(skyTexture);scene.environment=environment.texture;pmrem.dispose();skyTexture.dispose();
// One shared photographic-style albedo across all generated fruit materials.
let rindLoaded=false,rindTexture;
const rindReady=new Promise(resolve=>{
 rindTexture=new T.TextureLoader().load('assets/references/pumpkin-rind-albedo.png',()=>{
  rindLoaded=true;scene.traverse(o=>{if(o.material?.name==='fruit'){o.material.map=rindTexture;o.material.needsUpdate=true;}});resolve(true);
 },undefined,()=>{console.warn('Rind texture unavailable; using procedural skin.');resolve(false);});
 rindTexture.encoding=T.sRGBEncoding;rindTexture.wrapS=rindTexture.wrapT=T.RepeatWrapping;rindTexture.repeat.set(2,1);rindTexture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
});
let patch,kit,model,view='field',buildMs=0,frames=0,last=performance.now(),fps=0,regenTimer,paintMode=null,extras=[];
if(matchMedia('(min-width:900px)').matches)$('tier').value='medium';
const varianceGroups=[
['Pumpkin variation',[
['pumpkinWidth','Fruit width',.5,1.8,.05,1,'x'],['pumpkinHeight','Fruit height',.4,1.8,.05,1,'x'],['ribCount','Rib count',5,18,1,10,''],['ribDepth','Rib depth',0,.23,.01,.1,''],['stemCurl','Stem curl',0,2.5,.1,1,'x'],['sizeMin','Minimum plant size',.2,2,.05,.75,'x'],['sizeMax','Maximum plant size',.2,2.5,.05,1.25,'x']]],
['Vine variation',[
['internode','Node spacing',.15,.9,.05,.3,' m'],['branchAngle','Branch spread',.2,1.5,.05,.7,' rad'],['vineCurl','Runner meander',0,2.5,.1,1,'x'],['vineThickness','Runner thickness',.5,2,.1,1,'x'],['tendrilTurns','Tendril coils',1,5,.25,2,' turns']]],
['Flower variation',[
['flowerDensity','Blossom frequency',0,2,.1,.4,'x'],['flowerSize','Blossom size',.4,2,.1,1,'x'],['flowerOpen','Blossom opening',.15,1,.05,1,''],['flowerPetals','Petal count',4,8,1,5,'']]],
['Trellis variation',[
['trellisWidth','Support width',1,5,.1,2.4,' m'],['trellisHeight','Support height',1.8,4,.1,2.5,' m'],['trellisLength','Arch depth',1,6,.1,2,' m'],['archRise','Arch crown rise',.25,2.5,.05,1.2,' m'],['railSpacing','Rail spacing',.2,.8,.05,.35,' m'],['supportThickness','Support thickness',.5,2,.1,1,'x']]]
];
const varianceFields=[['variation','Natural variation',0,1,.05,.5,'']];
function addSlider(parent,f){const [id,title,min,max,step,value,unit]=f,label=document.createElement('label');label.htmlFor=id;label.append(title);const output=document.createElement('output');output.id=id+'Out';label.append(output);const input=document.createElement('input');Object.assign(input,{type:'range',id,min,max,step,value});input.dataset.unit=unit;parent.append(label,input);}
const section=document.createElement('div');section.id='varianceControls';const note=document.createElement('p');note.className='subtle';note.textContent='Shape the components below. Seeded variation changes size and irregularity; zero keeps those proportions uniform. Mixed shape/color still mix cultivars.';section.append(note);addSlider(section,varianceFields[0]);
for(const [title,fields] of varianceGroups){const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent=title;detail.append(summary);fields.forEach(f=>{addSlider(detail,f);varianceFields.push(f);});if(title.startsWith('Flower')){const n=document.createElement('p');n.className='subtle';n.textContent='Five petals is typical for squash. Other counts are artistic variants. Late fall and overripe plants suppress blossoms; Flower view always shows the selected form.';detail.append(n);}if(title.startsWith('Trellis')){const n=document.createElement('p');n.className='subtle';n.textContent='Depth and crown rise apply to metal arches. Climbing paths follow the same support dimensions.';detail.append(n);}section.append(detail);}
$('panel').insertBefore(section,$('panel').querySelector('details'));
const componentSections=section.querySelectorAll('details');for(const [index,ids] of [[0,['shape','color']],[1,['vineLength','branching']]])for(const id of ids){const input=$(id),label=input.previousElementSibling;componentSections[index].append(label,input);}
function updateReadouts(){for(const [id,,,,,unit] of varianceFields)$(id+'Out').textContent=Number($(id).value).toFixed(2).replace(/\.00$/,'')+unit;}
updateReadouts();

function settings(){const o={};for(const k of ['seed','density','scale','season','tier','trellis','width','length','growth','shape','color','vineLength','branching','leafDensity','health',...varianceFields.map(f=>f[0])])o[k]=$(k).value;o.climbing=$('climbing').checked;return A.options(o);}
const height=(x,z)=>$('terrain').checked?.08*Math.sin(x*.6)*Math.cos(z*.55):0;
function clear(){patch?.dispose();patch=null;if(model){model.userData.materials?.forEach(m=>m.dispose());scene.remove(model);model.traverse(m=>{if(m.isInstancedMesh)m.dispose?.();if(m.userData.owned)m.geometry.dispose();});model=null;}if(kit){kit.dispose();kit=null;}extras.forEach(p=>p.dispose());extras=[];}
function mesh(g,m,parent,x=0,y=0,z=0,s=1){const obj=new T.Mesh(g,m);obj.position.set(x,y,z);obj.scale.setScalar(s);obj.castShadow=true;obj.receiveShadow=true;parent.add(obj);return obj;}
function generate(reframe=false){try{const start=performance.now(),o=settings();clear();kit=A.createKit(T,(['pumpkin','flower','leaf'].includes(view)&&o.tier==='mobile')?'medium':o.tier,{...o,inspection:view==='pumpkin'});if(rindLoaded)kit.materials.fruit.map=rindTexture;for(const m of Object.values(kit.materials))m.envMapIntensity=m.metalness>.5?.65:.23;renderer.setPixelRatio(Math.min(devicePixelRatio,o.tier==='high'?2:1.25));sun.shadow.mapSize.set(o.tier==='high'?2048:1024,o.tier==='high'?2048:1024);sun.shadow.map?.dispose();sun.shadow.map=null;
 const P=ground.geometry.attributes.position;for(let i=0;i<P.count;i++)P.setZ(i,height(P.getX(i),-P.getY(i))-.025);P.needsUpdate=true;ground.geometry.computeVertexNormals();
 if(view==='field'||view==='trellis'||view==='vine'){const config={...o};if(view==='trellis'){config.width=3.8;config.length=3.5;config.density=.22;if(config.trellis==='off')config.trellis='arch';}if(view==='vine'){config.width=1;config.length=1;config.density=1;config.trellis='off';}patch=A.build(T,config,{heightAt:height},kit);scene.add(patch.root);}else{model=new T.Group();scene.add(model);if(view==='pumpkin'){for(let i=0;i<7;i++){const focus=document.getElementById('fruitFocus')?.value||'all';if(focus!=='all'&&i!==Number(focus))continue;const x=focus==='all'?(i%4-1.5)*1.5:0,z=focus==='all'?Math.floor(i/4)*1.65-.5:0,random=A.rng(o.seed+i*71),ps=o.scale*(1+(random()-.5)*o.variation*.6);const m=kit.materials.fruit.clone();m.color.setHex([0xcd641c,0xc96b24,0xd59036,0xb45f2b,0xe2d8b6,0x687450,0xad813e][i]).convertSRGBToLinear();model.userData.materials??=[];model.userData.materials.push(m);mesh(kit.fruit(i),m,model,x,height(x,z),z,ps);mesh(kit.stem(i),kit.materials.stem,model,x,height(x,z),z,ps);}}else if(view==='flower'){const random=A.rng(o.seed);for(let i=0;i<3;i++){const x=(i-1)*.28,z=i===1?-.22:.1,scale=o.scale*o.flowerSize*(1+(random()-.5)*o.variation*.5),y=.22+random()*.08*o.variation;mesh(kit.flower(),kit.materials.flower,model,x,y,z,scale);const stem=kit.tube([[x,0,z],[x-.03,y*.6,z],[x,y,z]],.006,5),m=mesh(stem,kit.materials.vine,model);m.userData.owned=true;}}else{const lm=kit.materials.leaf.clone();lm.color.setHex(o.health==='green'?0x56883a:o.health==='yellow'?0xc1b85d:0x8c7b46).convertSRGBToLinear();model.userData.materials=[lm];const g=mesh(kit.leaf(0),lm,model,0,.13,0,o.scale*3);mesh(kit.veins(),kit.materials.vein,model,0,.13,0,o.scale*3);g.rotation.x=.1;}}
 buildMs=performance.now()-start;updateReadouts();$('error').textContent='';for(const k of ['density','scale','growth'])$(k+'Out').textContent=$(k).value+(k==='density'?' / m²':k==='scale'?'×':'');$('loading').hidden=true;window.dispatchEvent(new CustomEvent('autumn:generated'));if(reframe)frameView();return true;
 }catch(e){$('error').textContent=e.stack;console.error(e);return false;}}
function frameView(){const object=patch?.root||model;if(!object)return;object.updateMatrixWorld(true);const box=new T.Box3().setFromObject(object);if(view==='field'&&window.autumnGarden?.root.visible)box.expandByObject(window.autumnGarden.root);const size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),halfV=T.MathUtils.degToRad(camera.fov/2),halfH=Math.atan(Math.tan(halfV)*camera.aspect),d=Math.max(.8,size.length()*.5/Math.sin(Math.min(halfV,halfH))*1.1);controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(.7,.62,1).normalize().multiplyScalar(d));controls.maxDistance=Math.max(85,d*1.4);camera.far=Math.max(180,d*3);camera.updateProjectionMatrix();const span=Math.max(2,Math.min(35,size.length()*.65));sun.position.copy(center).add(new T.Vector3(-8,13,7));sun.target.position.copy(center);scene.add(sun.target);Object.assign(sun.shadow.camera,{left:-span,right:span,top:span,bottom:-span});sun.shadow.camera.updateProjectionMatrix();controls.update();window.autumnGarden?.applyLighting();}
const captions={flower:['Blossoms, from bud to open.','Change size, opening and petal count. Seeded variation keeps each blossom a little different.'],field:['A field, grown from a seed.','Ribbed fruit, branching runners and curled leaves. Every variation is repeatable.'],pumpkin:['Seven harvest silhouettes.','Round, tall, squat, flattened, white, green and warty. Recessed sockets and curved woody stems.'],leaf:['Follow the veins.','Lobed, cupped leaves with thickness, branching veins and a lighter underside.'],vine:['Everything connects.','Runners, petioles, coiled tendrils and blossoms share a connected structure.'],trellis:['A garden reaching upward.','Climbing runners wind around the support, sending leaves outward toward the light.']};
function setView(v){view=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('caption').innerHTML='<strong>'+captions[v][0]+'</strong><p>'+captions[v][1]+'</p>';generate(true);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('aside input,aside select').forEach(e=>e.addEventListener('input',()=>{updateReadouts();if(e.id==='sizeMin'&&+$('sizeMin').value>+$('sizeMax').value)$('sizeMax').value=e.value;if(e.id==='sizeMax'&&+$('sizeMax').value<+$('sizeMin').value)$('sizeMin').value=e.value;clearTimeout(regenTimer);regenTimer=setTimeout(()=>generate(false),170);}));$('shuffle').onclick=()=>{$('seed').value=(+ $('seed').value+1)>>>0;generate();};$('reset').onclick=frameView;$('controlsToggle').onclick=()=>{const open=$('panel').classList.toggle('open');document.body.classList.toggle('controls-open',open);$('controlsToggle').textContent=open?'Close ↓':'Controls ↑';$('controlsToggle').setAttribute('aria-expanded',open);};
for(const mode of ['place','paint','orbit'])$(mode).onclick=()=>{paintMode=mode==='orbit'?null:mode;controls.enabled=!paintMode;for(const m of ['place','paint','orbit'])$(m).classList.toggle('active',m===mode);};const ray=new T.Raycaster(),pointer=new T.Vector2();canvas.addEventListener('pointerdown',e=>{if(!paintMode||view!=='field'||extras.length>=30)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(ground)[0];if(!hit)return;const p=hit.point,o=settings(),s=paintMode==='place'?1:3,remaining=A.TIERS[o.tier].maxPlants-(patch?.data.plants.length||0)-extras.reduce((n,p)=>n+p.data.plants.length,0);if(remaining<1){$('progress').textContent='Plant budget reached for this quality tier.';return;}const extra=A.build(T,{...o,seed:o.seed+extras.length+100,width:s,length:s,density:Math.min(paintMode==='place'?1:1.1,remaining/(s*s)),trellis:'off'},{heightAt:(x,z)=>height(x+p.x,z+p.z)},kit);extra.root.position.set(p.x,0,p.z);scene.add(extra.root);extras.push(extra);});
function exportScene(source){
 const out=new T.Group(),materials=new Map();out.name=source.name;out._temporaryMaterials=[];source.updateMatrixWorld(true);
 source.traverse(obj=>{if(!obj.isMesh||!obj.visible)return;let a=obj.parent;while(a&&a!==source){if(!a.visible)return;a=a.parent;}
  if(obj.isInstancedMesh){for(let i=0;i<obj.count;i++){
   const matrix=new T.Matrix4();obj.getMatrixAt(i,matrix);matrix.premultiply(obj.matrixWorld);
   const color=new T.Color();if(obj.instanceColor)obj.getColorAt(i,color);
   const key=obj.material.uuid+':'+color.toArray().join(',');let mat=materials.get(key);
   if(!mat){mat=obj.material.clone();mat.color.multiply(color);materials.set(key,mat);out._temporaryMaterials.push(mat);}
   const item=new T.Mesh(obj.geometry,mat);item.name=obj.name||obj.parent.name;item.applyMatrix4(matrix);out.add(item);
  }}else{const item=new T.Mesh(obj.geometry,obj.material);item.name=obj.name||obj.parent.name;item.applyMatrix4(obj.matrixWorld);out.add(item);}
 });return out;
}
async function glb(source){
 await rindReady;const out=new T.Group(),sources=source?[source]:[patch?.root||model,...extras.map(p=>p.root),...(view==='field'&&window.autumnGarden?[window.autumnGarden.root]:[])];
 sources.filter(Boolean).forEach(s=>out.add(exportScene(s)));
 try{return await new Promise((resolve,reject)=>new T.GLTFExporter().parse(out,resolve,reject,{binary:true,onlyVisible:true}));}
 finally{out.children.forEach(g=>g._temporaryMaterials?.forEach(m=>m.dispose()));}
}
$('export').onclick=async()=>{try{$('progress').textContent='Exporting visible geometry…';const bytes=await glb(),url=URL.createObjectURL(new Blob([bytes],{type:'model/gltf-binary'})),a=document.createElement('a');a.href=url;a.download='autumn-'+view+'-'+$('seed').value+'.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('progress').textContent='GLB exported.';}catch(e){$('progress').textContent='Export failed: '+e.message;}};
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').textContent='Graphics paused by the browser. Reload to restore the preview.';});window.addEventListener('error',e=>{$('error').textContent=e.message;});resize();generate(true);
function render(now){requestAnimationFrame(render);if(document.hidden)return;controls.update();if(patch){patch.update(camera,now/1000);patch.chunks.forEach(c=>c.g.visible=true);}extras.forEach(p=>p.update(camera,now/1000));if(kit)kit.clock.value=now/1000;window.autumnGarden?.update(now/1000);renderer.render(scene,camera);frames++;if(now-last>700){fps=Math.round(frames*1000/(now-last));frames=0;last=now;const s=patch?.stats();$('stats').innerHTML=fps+' FPS · '+renderer.info.render.calls+' draws<br>'+Math.round(renderer.info.render.triangles/1000)+'k triangles · '+(s?s.plants+' plants':'Detail inspection')+'<br>'+Math.round(buildMs)+' ms build'+(s?.capped?' · budget capped':'');}}
requestAnimationFrame(render);window.autumnPreview={get patch(){return patch;},get model(){return model;},get kit(){return kit;},renderer,scene,camera,controls,ground,sun,frameView,rindReady,get view(){return view;},settings,generate,setView,glb,exportScene,get stats(){return {fps,buildMs,render:{...renderer.info.render},memory:{...renderer.info.memory},patch:patch?.stats()};}};
})();
