(function(){'use strict';
const $=id=>document.getElementById(id),T=THREE,A=AutumnAssets,canvas=$('view');let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('error').textContent='3D could not start. Close other browser tabs and reload. '+e.message;return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color(0x8fa2a1);scene.fog=new T.Fog(0x8fa2a1,45,100);const camera=new T.PerspectiveCamera(43,1,.015,180),controls=new T.OrbitControls(camera,canvas);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=.35;controls.maxDistance=85;controls.target.set(0,.25,0);camera.position.set(8,7,11);
scene.add(new T.HemisphereLight(0xd6e9f2,0x62502b,.95));const sun=new T.DirectionalLight(0xffecc9,1.9);sun.position.set(-8,13,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-18,right:18,top:18,bottom:-18,near:1,far:60});sun.shadow.bias=-.0002;sun.shadow.normalBias=.018;scene.add(sun);scene.add(new T.AmbientLight(0xffffff,.12));
const soilCanvas=document.createElement('canvas');soilCanvas.width=soilCanvas.height=256;const ctx=soilCanvas.getContext('2d'),im=ctx.createImageData(256,256),rand=A.rng(77);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const v=rand()*28+Math.sin(x*.45)*7,i=(y*256+x)*4;im.data.set([77+v,62+v,39+v,255],i);}ctx.putImageData(im,0,0);const soilMap=new T.CanvasTexture(soilCanvas);soilMap.wrapS=soilMap.wrapT=T.RepeatWrapping;soilMap.repeat.set(12,12);soilMap.encoding=T.sRGBEncoding;const soilMat=new T.MeshStandardMaterial({map:soilMap,roughness:1});const ground=new T.Mesh(new T.PlaneGeometry(150,150,70,70),soilMat);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
let patch,kit,model,view='field',buildMs=0,frames=0,last=performance.now(),fps=0,regenTimer,paintMode=null,extras=[];
if(matchMedia('(min-width:900px)').matches)$('tier').value='medium';
function settings(){const o={};for(const k of ['seed','density','scale','season','tier','trellis','width','length','growth','shape','color','vineLength','branching','leafDensity','health'])o[k]=$(k).value;o.climbing=$('climbing').checked;return A.options(o);}
const height=(x,z)=>$('terrain').checked?.08*Math.sin(x*.6)*Math.cos(z*.55):0;
function clear(){patch?.dispose();patch=null;if(model){model.userData.materials?.forEach(m=>m.dispose());scene.remove(model);model.traverse(m=>{if(m.isInstancedMesh)m.dispose?.();if(m.userData.owned)m.geometry.dispose();});model=null;}if(kit){kit.dispose();kit=null;}extras.forEach(p=>p.dispose());extras=[];}
function mesh(g,m,parent,x=0,y=0,z=0,s=1){const obj=new T.Mesh(g,m);obj.position.set(x,y,z);obj.scale.setScalar(s);obj.castShadow=true;obj.receiveShadow=true;parent.add(obj);return obj;}
function generate(reframe=false){try{const start=performance.now(),o=settings();clear();kit=A.createKit(T,o.tier);renderer.setPixelRatio(Math.min(devicePixelRatio,o.tier==='high'?2:1.25));sun.shadow.mapSize.set(o.tier==='high'?2048:1024,o.tier==='high'?2048:1024);sun.shadow.map?.dispose();sun.shadow.map=null;
 const P=ground.geometry.attributes.position;for(let i=0;i<P.count;i++)P.setZ(i,height(P.getX(i),-P.getY(i))-.025);P.needsUpdate=true;ground.geometry.computeVertexNormals();
 if(view==='field'||view==='trellis'||view==='vine'){const config={...o};if(view==='trellis'){config.width=3.8;config.length=3.5;config.density=.22;if(config.trellis==='off')config.trellis='arch';}if(view==='vine'){config.width=1;config.length=1;config.density=1;config.trellis='off';}patch=A.build(T,config,{heightAt:height},kit);scene.add(patch.root);}else{model=new T.Group();scene.add(model);if(view==='pumpkin'){for(let i=0;i<7;i++){const x=(i%4-1.5)*1.05,z=Math.floor(i/4)*1.15-.5;const m=kit.materials.fruit.clone();m.color.setHex([0xe87c1c,0xd56b14,0xd9922f,0xc37a32,0xebe0bb,0x647958,0xc58d3c][i]).convertSRGBToLinear();model.userData.materials??=[];model.userData.materials.push(m);mesh(kit.fruit(i),m,model,x,height(x,z),z,o.scale);mesh(kit.stem(i),kit.materials.stem,model,x,height(x,z),z,o.scale);}}else{const lm=kit.materials.leaf.clone();lm.color.setHex(o.health==='green'?0x56883a:o.health==='yellow'?0xc1b85d:0x8c7b46).convertSRGBToLinear();model.userData.materials=[lm];const g=mesh(kit.leaf(0),lm,model,0,.13,0,o.scale*3);mesh(kit.veins(),kit.materials.vein,model,0,.13,0,o.scale*3);g.rotation.x=.1;}}
 buildMs=performance.now()-start;for(const k of ['density','scale','growth'])$(k+'Out').textContent=$(k).value+(k==='density'?' / m²':k==='scale'?'×':'');$('loading').hidden=true;if(reframe)frameView();return true;
 }catch(e){$('error').textContent=e.stack;console.error(e);return false;}}
function frameView(){const object=patch?.root||model;if(!object)return;object.updateMatrixWorld(true);const box=new T.Box3().setFromObject(object),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),halfV=T.MathUtils.degToRad(camera.fov/2),halfH=Math.atan(Math.tan(halfV)*camera.aspect),d=Math.max(.8,size.length()*.5/Math.sin(Math.min(halfV,halfH))*1.1);controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(.7,.62,1).normalize().multiplyScalar(d));controls.maxDistance=Math.max(85,d*1.4);camera.far=Math.max(180,d*3);camera.updateProjectionMatrix();controls.update();}
const captions={field:['A field, grown from a seed.','Ribbed fruit, branching runners and curled leaves. Every variation is repeatable.'],pumpkin:['Seven harvest silhouettes.','Round, tall, squat, flattened, white, green and warty. Recessed sockets and curved woody stems.'],leaf:['Follow the veins.','Lobed, cupped leaves with thickness, branching veins and a lighter underside.'],vine:['Everything connects.','Runners, petioles, coiled tendrils and blossoms share a connected structure.'],trellis:['A garden reaching upward.','Climbing runners wind around the support, sending leaves outward toward the light.']};
function setView(v){view=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('caption').innerHTML='<strong>'+captions[v][0]+'</strong><p>'+captions[v][1]+'</p>';generate(true);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('aside input,aside select').forEach(e=>e.addEventListener('input',()=>{clearTimeout(regenTimer);regenTimer=setTimeout(()=>generate(false),170);}));$('shuffle').onclick=()=>{$('seed').value=(+ $('seed').value+1)>>>0;generate();};$('reset').onclick=frameView;$('controlsToggle').onclick=()=>{const open=$('panel').classList.toggle('open');document.body.classList.toggle('controls-open',open);$('controlsToggle').textContent=open?'Close ↓':'Controls ↑';$('controlsToggle').setAttribute('aria-expanded',open);};
for(const mode of ['place','paint','orbit'])$(mode).onclick=()=>{paintMode=mode==='orbit'?null:mode;controls.enabled=!paintMode;for(const m of ['place','paint','orbit'])$(m).classList.toggle('active',m===mode);};const ray=new T.Raycaster(),pointer=new T.Vector2();canvas.addEventListener('pointerdown',e=>{if(!paintMode||view!=='field'||extras.length>=30)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(ground)[0];if(!hit)return;const p=hit.point,o=settings(),s=paintMode==='place'?1:3,remaining=A.TIERS[o.tier].maxPlants-(patch?.data.plants.length||0)-extras.reduce((n,p)=>n+p.data.plants.length,0);if(remaining<1){$('progress').textContent='Plant budget reached for this quality tier.';return;}const extra=A.build(T,{...o,seed:o.seed+extras.length+100,width:s,length:s,density:Math.min(paintMode==='place'?1:1.1,remaining/(s*s)),trellis:'off'},{heightAt:(x,z)=>height(x+p.x,z+p.z)},kit);extra.root.position.set(p.x,0,p.z);scene.add(extra.root);extras.push(extra);});
function exportScene(source){const out=new T.Group();source.updateMatrixWorld(true);source.traverse(obj=>{if(!obj.isMesh||!obj.visible)return;let a=obj.parent;while(a&&a!==source){if(!a.visible)return;a=a.parent;}if(obj.isInstancedMesh){for(let i=0;i<obj.count;i++){const m=new T.Matrix4();obj.getMatrixAt(i,m);m.premultiply(obj.matrixWorld);const mat=obj.material.clone();if(obj.instanceColor){const c=new T.Color();obj.getColorAt(i,c);mat.color.multiply(c);}const item=new T.Mesh(obj.geometry,mat);item.applyMatrix4(m);out.add(item);}}else{const item=new T.Mesh(obj.geometry,obj.material);item.applyMatrix4(obj.matrixWorld);out.add(item);}});return out;}
async function glb(source=patch?.root||model){return new Promise((resolve,reject)=>new T.GLTFExporter().parse(exportScene(source),resolve,reject,{binary:true,onlyVisible:true}));}
$('export').onclick=async()=>{try{$('progress').textContent='Exporting visible geometry…';const bytes=await glb(),url=URL.createObjectURL(new Blob([bytes],{type:'model/gltf-binary'})),a=document.createElement('a');a.href=url;a.download='autumn-'+view+'-'+$('seed').value+'.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('progress').textContent='GLB exported.';}catch(e){$('progress').textContent='Export failed: '+e.message;}};
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').textContent='Graphics paused by the browser. Reload to restore the preview.';});window.addEventListener('error',e=>{$('error').textContent=e.message;});resize();generate(true);
function render(now){requestAnimationFrame(render);if(document.hidden)return;controls.update();if(patch){patch.update(camera,now/1000);patch.chunks.forEach(c=>c.g.visible=true);}extras.forEach(p=>p.update(camera,now/1000));if(kit)kit.clock.value=now/1000;renderer.render(scene,camera);frames++;if(now-last>700){fps=Math.round(frames*1000/(now-last));frames=0;last=now;const s=patch?.stats();$('stats').innerHTML=fps+' FPS · '+renderer.info.render.calls+' draws<br>'+Math.round(renderer.info.render.triangles/1000)+'k triangles · '+(s?s.plants+' plants':'Detail inspection')+'<br>'+Math.round(buildMs)+' ms build'+(s?.capped?' · budget capped':'');}}
requestAnimationFrame(render);window.autumnPreview={get patch(){return patch;},get model(){return model;},get kit(){return kit;},renderer,scene,camera,controls,settings,generate,setView,glb,exportScene,get stats(){return {fps,buildMs,render:{...renderer.info.render},memory:{...renderer.info.memory},patch:patch?.stats()};}};
})();
