(function(){'use strict';
const T=THREE,F=FallScenery,$=id=>document.getElementById(id);let renderer;
try{renderer=new T.WebGLRenderer({canvas:$('view'),antialias:true,powerPreference:'high-performance'});}catch(e){$('error').textContent='Could not start 3D: '+e.message;return;}
renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(43,1,.03,300),controls=new T.OrbitControls(camera,$('view'));controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.495;controls.minDistance=1.4;controls.maxDistance=160;
const sky=new T.HemisphereLight(0xb8d2de,0x735c39,.8),sun=new T.DirectionalLight(0xffddab,2.1);sun.castShadow=true;sun.shadow.bias=-.0002;sun.shadow.normalBias=.035;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:110});scene.add(sky,sun,sun.target);
const height=(x,z)=>.12*Math.sin(x*.35)*Math.cos(z*.28)+.04*Math.sin(x*1.3+z*.8);
const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),im=ctx.createImageData(512,512),r=F.rng(301);
const hash=(x,y)=>{let n=Math.imul(x,374761393)+Math.imul(y,668265263);n=Math.imul(n^(n>>>13),1274126177);return((n^(n>>>16))>>>0)/4294967295;};
const noise=(x,y)=>{const ix=Math.floor(x),iy=Math.floor(y);let u=x-ix,v=y-iy;u=u*u*(3-2*u);v=v*v*(3-2*v);return (hash(ix,iy)*(1-u)+hash(ix+1,iy)*u)*(1-v)+(hash(ix,iy+1)*(1-u)+hash(ix+1,iy+1)*u)*v;};
for(let y=0;y<512;y++)for(let x=0;x<512;x++){const grain=r(),v=grain*18+noise(x/39,y/39)*25+noise(x/12,y/12)*18+noise(x/3,y/3)*9,i=(y*512+x)*4,stone=grain>.995?28:0;im.data.set([52+v+stone,43+v*.88+stone,29+v*.68+stone,255],i);}
ctx.putImageData(im,0,0);const soil=new T.CanvasTexture(c);soil.wrapS=soil.wrapT=T.RepeatWrapping;soil.repeat.set(55,55);soil.encoding=T.sRGBEncoding;soil.anisotropy=renderer.capabilities.getMaxAnisotropy();
const ground=new T.Mesh(new T.PlaneGeometry(180,180,180,180),new T.MeshStandardMaterial({map:soil,bumpMap:soil,bumpScale:.035,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;const gp=ground.geometry.attributes.position;for(let i=0;i<gp.count;i++)gp.setZ(i,height(gp.getX(i),-gp.getY(i))-.02);ground.geometry.computeVertexNormals();scene.add(ground);
// Low contrast sky gradient also supplies soft image based fill to bark and fruit.
const skyCanvas=document.createElement('canvas');skyCanvas.width=512;skyCanvas.height=256;const skyCtx=skyCanvas.getContext('2d');let environment;
const dome=new T.Mesh(new T.SphereGeometry(170,32,18),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,fog:false,uniforms:{zenith:{value:new T.Color()},horizon:{value:new T.Color()}},vertexShader:'varying vec3 skyDirection;void main(){skyDirection=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 zenith;uniform vec3 horizon;varying vec3 skyDirection;void main(){float h=pow(max(0.,normalize(skyDirection).y),.55);gl_FragColor=vec4(mix(horizon,zenith,h),1.);\n#include <tonemapping_fragment>\n#include <encodings_fragment>\n}'}));dome.renderOrder=-1;scene.add(dome);
function lighting(){const presets={golden:{top:'#658395',horizon:'#e4c8a0',fog:0xc5bba2,color:0xffd295,power:2.6,sky:.65,exposure:.92,pos:[-24,15,18]},day:{top:'#608dad',horizon:'#d3dfdf',fog:0xb9c7c8,color:0xfff1dc,power:2.2,sky:.9,exposure:.96,pos:[-15,32,20]},overcast:{top:'#7d8a8e',horizon:'#c5c9c5',fog:0xa8b2ae,color:0xe8eff1,power:.7,sky:1.0,exposure:.94,pos:[-15,28,18]},dusk:{top:'#233e62',horizon:'#b48d79',fog:0x747f8d,color:0xf7b875,power:.65,sky:.38,exposure:.8,pos:[-25,9,20]}};const p=presets[$('light').value],gradient=skyCtx.createLinearGradient(0,0,0,256);gradient.addColorStop(0,p.top);gradient.addColorStop(.53,p.horizon);gradient.addColorStop(1,'#463a28');skyCtx.fillStyle=gradient;skyCtx.fillRect(0,0,512,256);const t=new T.CanvasTexture(skyCanvas);t.mapping=T.EquirectangularReflectionMapping;t.encoding=T.sRGBEncoding;const pm=new T.PMREMGenerator(renderer),e=pm.fromEquirectangular(t);environment?.dispose();environment=e;scene.environment=e.texture;scene.background=new T.Color(p.fog).convertSRGBToLinear();scene.fog=new T.Fog(new T.Color(p.fog).convertSRGBToLinear(),58,150);dome.material.uniforms.zenith.value.set(p.top).convertSRGBToLinear();dome.material.uniforms.horizon.value.set(p.horizon).convertSRGBToLinear();sun.color.setHex(p.color);sun.intensity=p.power;sun.position.set(...p.pos);sky.intensity=p.sky;renderer.toneMappingExposure=p.exposure;pm.dispose();t.dispose();}
const fields=['seed','tier','species','season','width','length','treeDensity','treeScale','canopyDensity','grassDensity','leafLitter','colorBias','pumpkinDensity','trellisCount'];let built,timer,buildMs=0,generation=0;const foliageKit=F.createKit(T);
function settings(){const o={};fields.forEach(k=>o[k]=$(k).value);for(const k of ['includePumpkins','includeTrellis'])o[k]=$(k).checked;return F.options(o);}
function frame(){if(!built)return;const box=new T.Box3().setFromObject(built.root),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),angle=T.MathUtils.degToRad(camera.fov/2),d=Math.max(size.y,size.x/camera.aspect,size.z)*.65/Math.tan(angle);controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(.7,.45,1).normalize().multiplyScalar(d));controls.update();}
async function generate(reframe=false){const token=++generation;$('progress').textContent='Loading the Sylva foliage pack…';try{const start=performance.now(),next=await F.build(T,settings(),{heightAt:height},foliageKit);if(token!==generation){next.dispose();return false;}built?.dispose();built=next;scene.add(built.root);buildMs=performance.now()-start;renderer.setPixelRatio(Math.min(devicePixelRatio,settings().tier==='high'?1.75:1.25));document.querySelectorAll('input[type=range]').forEach(e=>e.previousElementSibling.querySelector('output').textContent=e.value);$('error').textContent='';$('progress').textContent='Sylva foliage ready · drag to orbit.';if(reframe)frame();return true;}catch(e){if(token!==generation)return false;$('error').textContent=e.message;$('progress').textContent='';console.error(e);return false;}}

function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();lighting();if(matchMedia('(max-width:700px)').matches){$('tier').value='mobile';$('panel').hidden=true;$('toggle').textContent='Controls ↑';$('toggle').setAttribute('aria-expanded','false');}
$('toggle').onclick=()=>{const open=$('panel').hidden;$('panel').hidden=!open;document.body.classList.toggle('editing',open);$('toggle').textContent=open?'Hide controls ↓':'Controls ↑';$('toggle').setAttribute('aria-expanded',String(open));};$('frame').onclick=frame;$('shuffle').onclick=()=>{$('seed').value=(+$('seed').value+1)>>>0;generate();};$('light').oninput=lighting;
for(const id of [...fields,'includePumpkins','includeTrellis'])$(id).addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>generate(),220);});
async function glb(){if(!built)throw Error('Wait for the woodland to finish loading.');const out=new T.Group(),temp=[];built.root.updateMatrixWorld(true);built.root.traverse(m=>{if(!m.isMesh)return;let a=m.parent;while(a&&a!==built.root){if(!a.visible)return;a=a.parent;}if(!m.visible)return;if(m.isInstancedMesh){for(let i=0;i<m.count;i++){const matrix=new T.Matrix4();m.getMatrixAt(i,matrix);matrix.premultiply(m.matrixWorld);let mat=m.material;if(m.instanceColor){const col=new T.Color();m.getColorAt(i,col);mat=m.material.clone();mat.color.multiply(col);temp.push(mat);}const item=new T.Mesh(m.geometry,mat);item.applyMatrix4(matrix);out.add(item);}}else{const item=new T.Mesh(m.geometry,m.material);item.applyMatrix4(m.matrixWorld);out.add(item);}});try{return await new Promise((resolve,reject)=>new T.GLTFExporter().parse(out,resolve,reject,{binary:true}));}finally{temp.forEach(m=>m.dispose());}}
$('export').onclick=async()=>{const button=$('export');button.disabled=true;$('progress').textContent='Preparing the woodland export…';try{const bytes=await glb(),url=URL.createObjectURL(new Blob([bytes],{type:'model/gltf-binary'})),a=document.createElement('a');a.href=url;a.download='fall-scenery-'+$('seed').value+'.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('progress').textContent='Exported geometry and materials. Wind and sky lighting stay in the viewer.';}catch(e){$('progress').textContent='Export failed: '+e.message;}finally{button.disabled=false;}};
let frames=0,last=performance.now(),fps=0;function render(now){requestAnimationFrame(render);if(document.hidden)return;controls.update();dome.position.copy(camera.position);built?.update(camera,now/1000);renderer.render(scene,camera);if(now-last>900){fps=Math.round(frames*1000/(now-last));frames=0;last=now;const s=built?.stats();$('stats').innerHTML=(s?s.trees+' trees · '+s.source+' · LOD '+s.lod+'<br>'+s.litter.toLocaleString()+' fallen leaves · '+s.grass.toLocaleString()+' grass clumps<br>':'')+fps+' FPS · '+Math.round(renderer.info.render.triangles/1000)+'k triangles · '+Math.round(buildMs)+' ms build';}frames++;}
$('view').addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').textContent='Graphics paused. Reload to restore the scene.';});generate(true);requestAnimationFrame(render);window.fallPreview={renderer,scene,camera,controls,ground,sun,get built(){return built;},settings,generate,frame,lighting,glb};
})();
